### ISSUE TITLE
Issue running get_subdivided_merit_polygon function

### ISSUE THREAD

**Issue by kokubadejo** [mheberger/delineator#2]
When I run the delineator script, I come across this error:
`AttributeError: 'MultiPolygon' object has no attribute 'exterior'`
It stems from the line calling the get_subdivided_merit_polygon function in delineator
`    poly, lat_snap, lng_snap = py.merit_detailed.get_subdivided_merit_polygon(wid, basin, lat, lng, catchment_poly, bSingleCatchment)`

and subsequently in this line in the merit_detailed script:
`    filled_poly = Polygon(poly.exterior.coords)`

looks like my catchment_poly is a Multipolygon, so converting it to a polygon and then back to multipolygon doesn't work, but if I skip those steps, it still doesn't work

**Comment by mheberger** [comment]
Are you using the latest version from Github? I recall fixing an issue related to `MultiPolygon`s at one point. 

Can you include your `outlets.csv` file so I can debug? And also any settings in `config.py` that are not the defaults.

**Comment by mheberger** [comment]
Sorry, my comment wasn't clear. No one ever opened an issue related to this. It was a bug I found and fixed. But I didn't create a new version number or update the .zip download. 

Please try using version 1.1 (updated today). I just tried it with your basins file, and it worked fine. 

By the way, if you are only doing a small number of watersheds, you might try the web app: https://mghydro.com/watersheds.

**Comment by kokubadejo** [comment]
Thank you for this!
It seems I now get this error:
  ```
File "C:\Users\kokubade\OneDrive - University of Waterloo\Documents\Co-op Fall 2023 Docs\Watershed Delineation\Other Delineation Tools\Delineator\py\merit_detailed.py", line 337, in get_largest
    polygons = list(input_poly)
TypeError: 'MultiPolygon' object is not iterable
```

stemming from this line in delineate.py
```
poly, lat_snap, lng_snap = py.merit_detailed.get_subdivided_merit_polygon(wid, basin, lat, lng,
                                                                                          catchment_poly,
                                                                                          bSingleCatchment)
```

**Comment by mheberger** [comment]
I suspect that you have a different (newer) version of Shapely? Can you check that? I wrote the script with Shapely version 1.8.5.post1. I recall testing Shapely v2 and getting this error. 

I recommend creating a Python virtual environment in which to run the script, and installing the libraries with the version numbers listed in `requirements.txt`.

**Comment by mheberger** [comment]
I want to be able to help, but I can't reproduce your error. Are you working on the same outlet in the file `basins.csv` you included in your response above. If so, this line of the code should not even be reached. 

And if it is reached, line 337 in `merit_detailed.py` should work fine. A Shapely `MultiPolygon` is iterable in Shapely < 2.0, and you can convert it to a list of `Polygons`. 

I don't have experience with conda, but what do you get if you enter this in the console: `shapely.__version__`

**Comment by kokubadejo** [comment]
Hi, when  run the command it says
```
'shapely.__version__' is not recognized as an internal or external command,
operable program or batch file.
```

but when I check my list of conda packages I have 
`shapely                   1.8.5.post1              pypi_0    pypi`

I'm trying it out with the same outlet in my basins.csv file.

I'm not sure what's happening, but I created a python virtual env and ran it in that and it worked! (it warned about the compatibility of pygeos and shapely versions.

I'll try starting with a fresh conda env and install the packages individually to see if that would work too

**Comment by mheberger** [comment]
Great, glad it's working for you now. Sounds like your conda wasn't configured quite right.
