### ISSUE TITLE
Catchment file selection (Question)

### ISSUE THREAD

**Issue by kokubadejo** [mheberger/delineator#5]
How different are the standard catchment files to the ones marked 'minor bug fix for coastline pixels'. I tried batch delineating a couple of points using the standard catchment shapefiles, and for a point in basin 78, there seems to be a missing feature / gap in the polygon. I noticed that this is not the case in the bug-fixed file and was wondering which one was better to use in general

**Comment by mheberger** [comment]
I have not done a detailed comparison of the dataset versions. My
understanding is that the "bug fix" version had only very minor changes.

**Comment by kokubadejo** [comment]
Ahh okay, I guess the results shouldn't be significantly different then. Thanks!

**Comment by kokubadejo** [comment]
Also, are there any other files that have updates, or bug fixes?

**Comment by mheberger** [comment]
None that I am aware of. If HydroSHEDS v2 ever comes out, I will consider integrating that.
