### ISSUE TITLE
Coastal Points / Points outside basins

### ISSUE THREAD

**Issue by kokubadejo** [mheberger/delineator#6]
I'm trying to run the delineation on a batch of points, and some of them are outside the merit basins. I tried using the buffered merit basins but I run into a nan error cause it's outside of the catchment basins, so there's no terminal_comid for it. Is there a fix for this? What would you recommend I do so they are delineated?

Some of such points are:
{'id': 217697, 'lat': 49.348897, 'lng': -124.428403}
{'id': 217808, 'lat': 49.23117, 'lng': -123.97092}
{'id': 217714, 'lat': 50.6102, 'lng': -127.2367}

**Comment by mheberger** [comment]
Two thoughts on this:

(1) You can use my web app at https://mghydro.com/watersheds. I added the
MERIT-Basins "coastal catchments" layer to the dataset used by the app.

(2) BUT! These are very small watersheds in urbanized areas. You may not
get good results using MERIT-Hydro data, which are fairly coarse resolution
(3 arcsecond). This data is meant more for use in large-scale hydrology,
not local applications.

Your choices are to do a manual delineation with topo maps (if you only
have 3 points, should be fairly quick), or use higher-resolution elevation
data, e.g. I found this via a quick Google search:
https://open.canada.ca/data/en/dataset/957782bf-847c-4644-a757-e383c0057995

There's a decent list of software for this on Wikipedia:
https://en.wikipedia.org/wiki/Watershed_delineation#Software_for_watershed_delineation
